[tool.poetry]
name = "irrigation-pi"
version = "0.2.2"
description = ""
authors = ["Max Pfeiffer <max@maxpfeiffer.ch>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
alembic = "1.13.1"
APScheduler = "3.10.4"
asyncer = "0.0.4"
click = "8.1.7"
fastapi = "0.109.2"
furl = "2.1.3"
pydantic-settings = "2.2.1"
semver = "3.0.2"
sqlalchemy = "2.0.27"
sqlmodel = "0.0.16"
toml = "0.10.2"
uvicorn = {version = "0.27.1", extras = ["standard"]}

gpiozero = "2.0.1"
pigpio = "1.78"
"RPi.GPIO" = {version = "0.7.1", markers= "sys_platform == 'linux'"}

[tool.poetry.group.dev.dependencies]
coverage = "7.4.3"
pre-commit = "3.6.2"
pytest = "8.0.1"
pytest-asyncio = "0.23.5"
pytest-cov = "4.1.0"
httpx = "0.27.0"
ruff = "0.2.2"

[tool.poetry.scripts]
irrigation-pi = 'irrigation_pi:cli'

[tool.ruff]
exclude = [".venv", "backend/migrations", "frontend"]

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle
    "W", # pycodestyle
    "I", # isort
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "ASYNC", # flake8-async
    "RUF",  # Ruff-specific rules
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

# https://docs.pytest.org/en/latest/reference/customize.html
[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = [
    "irrigation_pi/tests",
    "backend/tests"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
