[tool.poetry]
name = "irrigation-pi"
version = "1.0.1"
description = ""
authors = ["Max Pfeiffer <max@maxpfeiffer.ch>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
alembic = "1.13.1"
APScheduler = "3.10.4"
asyncer = "0.0.7"
click = "8.1.7"
fastapi = "0.111.0"
furl = "2.1.3"
pydantic-settings = "2.2.1"
semver = "3.0.2"
sqlalchemy = "2.0.30"
sqlmodel = "0.0.18"
toml = "0.10.2"
uvicorn = {version = "0.29.0", extras = ["standard"]}

gpiozero = "2.0.1"
pigpio = "1.78"
"RPi.GPIO" = {version = "0.7.1", markers= "sys_platform == 'linux'"}

[tool.poetry.group.dev.dependencies]
coverage = "7.5.1"
pre-commit = "3.7.1"
pytest = "8.2.0"
pytest-asyncio = "0.23.6"
pytest-cov = "5.0.0"
httpx = "0.27.0"
ruff = "0.4.4"

[tool.poetry.scripts]
irrigation-pi = 'irrigation_pi:cli'

[tool.ruff]
exclude = [".venv", "backend/migrations", "frontend"]

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # pycodestyle
    "W", # pycodestyle
    "I", # isort
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "ASYNC", # flake8-async
    "RUF",  # Ruff-specific rules
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

# https://docs.pytest.org/en/latest/reference/customize.html
[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = [
    "irrigation_pi/tests",
    "backend/tests"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
