name: Code Quality

on:
  pull_request:
    paths:
      - .github/**
      - backend/**
      - irrigation_pi/**
      - uv.lock

jobs:
  code-quality:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          uv sync --locked
      - name: Run ruff
        run: |
          uv run pre-commit run -a
