name: Tests

on:
  pull_request:
    paths:
      - .github/**
      - backend/**
      - irrigation_pi/**
      - uv.lock

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          uv sync --locked
      - name: Run all tests with pytest
        run: |
          uv run pytest --cov --cov-report=xml:coverage_report.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage_report.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
